### ISSUE TITLE
link to XSD schema is 404

### ISSUE THREAD

**Issue by joelthill** [srnsw/ae#4]
Dear project team,

I am trying to find the schema file for your retention schedule, but it is not referenced as I expected, on [nsw.gov.au's XML schema for retention and disposal authorities page](https://www.records.nsw.gov.au/recordkeeping/advice/retention-and-disposal/xml-schema), nor is the link on [srnsw.github.io](http://srnsw.github.io/) working. Could you please point me towards the new location in case it has changed?

thanks in advance.
Joel

**Comment by richardlehane** [comment]
You can find an archived version here: https://web.archive.org/web/20160617185956/https://www.records.nsw.gov.au/schemas/rda/SRNSW_RDA.xsd/

**Comment by joelthill** [comment]
brilliant - thx.
j.
